spring.application.name=conversor_de_arquivos
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/conversor_de_arquivosdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always
server.error.include-stacktrace=never
